from pyray import *
from genie.services.constants.keys import *

"""
    This map maps the Genie consant id of each key to its partner in the Raylib framework.
    Some of the constants defined above are not found in this map because Raylib does not support
    such keys.
"""
keys_map = {
    BACKSPACE : KEY_BACKSPACE,
    TAB : KEY_TAB,
    # CLEAR : pygame.K_CLEAR,
    RETURN : KEY_ENTER,
    PAUSE : KEY_PAUSE,
    ESCAPE : KEY_ESCAPE,
    SPACE : KEY_SPACE,
    # EXCLAIM = pygame.K_EXCLAIM
    # DBL_QUOTE = pygame.K_QUOTEDBL
    # HASH = pygame.K_HASH
    # DOLLAR = pygame.K_DOLLAR
    # AMPERSAND = pygame.K_AMPERSAND
    QUOTE : KEY_APOSTROPHE,
    # LEFTPAREN = pygame.K_LEFTPAREN
    # RIGHTPAREN = pygame.K_RIGHTPAREN
    # ASTERISK = pygame.K_ASTERISK
    # PLUS = pygame.K_PLUS
    COMMA : KEY_COMMA,
    MINUS : KEY_MINUS,
    PERIOD : KEY_PERIOD,
    SLASH : KEY_SLASH,
    K_0 : KEY_ZERO,
    K_1 : KEY_ONE,
    K_2 : KEY_TWO,
    K_3 : KEY_THREE,
    K_4 : KEY_FOUR,
    K_5 : KEY_FIVE,
    K_6 : KEY_SIX,
    K_7 : KEY_SEVEN,
    K_8 : KEY_EIGHT,
    K_9 : KEY_NINE,
    # COLON : pygame.K_COLON,
    SEMICOLON : KEY_SEMICOLON,
    # LESS : pygame.K_LESS,
    EQUAL : KEY_EQUAL,
    # GREATER : pygame.K_GREATER,
    # QUESTION : pygame.K_QUESTION,
    # AT : pygame.K_AT,
    LEFT_BRACKET : KEY_LEFT_BRACKET,
    BACKSLASH : KEY_BACKSLASH,
    RIGHTBRACKET : KEY_RIGHT_BRACKET,
    # CARET : pygame.K_CARET,
    # UNDERSCORE : pygame.K_UNDERSCORE,
    BACKQUOTE : KEY_GRAVE,
    A : KEY_A,
    B : KEY_B,
    C : KEY_C,
    D : KEY_D,
    E : KEY_E,
    F : KEY_F,
    G : KEY_G,
    H : KEY_H,
    I : KEY_I,
    J : KEY_J,
    K : KEY_K,
    L : KEY_L,
    M : KEY_M,
    N : KEY_N,
    O : KEY_O,
    P : KEY_P,
    Q : KEY_Q,
    R : KEY_R,
    S : KEY_S,
    T : KEY_T,
    U : KEY_U,
    V : KEY_V,
    W : KEY_W,
    X : KEY_X,
    Y : KEY_Y,
    Z : KEY_Z,
    DELETE : KEY_DELETE,
    KP0 : KEY_KP_0,
    KP1 : KEY_KP_1,
    KP2 : KEY_KP_2,
    KP3 : KEY_KP_3,
    KP4 : KEY_KP_4,
    KP5 : KEY_KP_5,
    KP6 : KEY_KP_6,
    KP7 : KEY_KP_7,
    KP8 : KEY_KP_8,
    KP9 : KEY_KP_9,
    KP_PERIOD : KEY_KP_DECIMAL,
    KP_DIVIDE : KEY_KP_DIVIDE,
    KP_MULTIPLY : KEY_KP_MULTIPLY,
    KP_MINUS : KEY_KP_SUBTRACT,
    KP_PLUS : KEY_KP_ADD,
    KP_ENTER : KEY_KP_ENTER,
    KP_EQUAL : KEY_KP_EQUAL,
    UP : KEY_UP,
    DOWN : KEY_DOWN,
    LEFT : KEY_LEFT,
    RIGHT : KEY_RIGHT,
    INSERT : KEY_INSERT,
    HOME : KEY_HOME,
    END : KEY_END,
    PAGEUP : KEY_PAGE_UP,
    PAGEDOWN : KEY_PAGE_DOWN,
    F1 : KEY_F1,
    F2 : KEY_F2,
    F3 : KEY_F3,
    F4 : KEY_F4,
    F5 : KEY_F5,
    F6 : KEY_F6,
    F7 : KEY_F7,
    F8 : KEY_F8,
    F9 : KEY_F9,
    F10 : KEY_F10,
    F11 : KEY_F11,
    F12 : KEY_F12,
    # F13 : KEY_F13,
    # F14 : KEY_F14,
    # F15 : KEY_F15,
    NUMLOCK : KEY_NUM_LOCK,
    CAPSLOCK : KEY_CAPS_LOCK,
    SCROLLOCK : KEY_SCROLL_LOCK,
    RSHIFT : KEY_RIGHT_SHIFT,
    LSHIFT : KEY_LEFT_SHIFT,
    RCTRL : KEY_RIGHT_CONTROL,
    LCTRL : KEY_LEFT_CONTROL,
    RALT : KEY_RIGHT_ALT,
    LALT : KEY_LEFT_ALT,
    # RMETA : KEY_RMETA,
    # LMETA : KEY_LMETA,
    LSUPER : KEY_LEFT_SUPER,
    RSUPER : KEY_RIGHT_SUPER,
    # MODE : KEY_MODE,
    # HELP : KEY_HELP,
    PRINT : KEY_PRINT_SCREEN,
    # SYSREQ : KEY_SYSREQ,
    # BREAK : KEY_BREAK,
    MENU : KEY_MENU,
    KB_MENU : KEY_KB_MENU,
    # POWER : KEY_POWER,
    # EURO : KEY_EURO,
    VOLUME_UP : KEY_VOLUME_UP,
    VOLUME_DOWN : KEY_VOLUME_DOWN
}